<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="">
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project_Entity" lowerBound="1"
        upperBound="-1" eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project_Relationship" upperBound="-1"
        eType="#//Relationship" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Project_Domain" upperBound="-1"
        eType="#//Domain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entity_Primary_Key" lowerBound="1"
        eType="#//Primary_Key" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entity_Candidate_Key" upperBound="-1"
        eType="#//Candidate_Key" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Domain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship"/>
  <eClassifiers xsi:type="ecore:EClass" name="Child_Entity" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Weak_Entity" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Restriction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusive" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusiveness" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Exclusion" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inclusion" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Candidate_Key" eSuperTypes="#//Constraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Primary_Key" eSuperTypes="#//Candidate_Key"/>
</ecore:EPackage>
